version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://gyenbox:gyenbox@postgres:5432/gyenbox
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_BUCKET: gyenbox
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_FORCE_PATH_STYLE: "true"
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: change-me-in-development
    depends_on:
      - postgres
      - minio
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: gyenbox
      POSTGRES_PASSWORD: gyenbox
      POSTGRES_DB: gyenbox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  minio_data:
