import { FileItem, ActivityItem, CommentItem } from './types';

export const INITIAL_FILES: FileItem[] = [
  // Folders (at root)
  {
    id: 'f1',
    name: 'Brand_Assets',
    type: 'folder',
    itemCount: 45,
    size: '4.8 GB',
    sizeBytes: 4800000000,
    modifiedAt: '2h ago',
    createdAt: 'Jun 24, 2025',
    starred: true,
    shared: true,
    parentFolderId: null,
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },
  {
    id: 'f2',
    name: 'Project_Nexus',
    type: 'folder',
    itemCount: 12,
    size: '1.2 GB',
    sizeBytes: 1200000000,
    modifiedAt: '3d ago',
    createdAt: 'May 12, 2025',
    starred: false,
    shared: false,
    parentFolderId: null,
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },
  {
    id: 'f3',
    name: 'Exports',
    type: 'folder',
    itemCount: 8,
    size: '320 MB',
    sizeBytes: 320000000,
    modifiedAt: 'Yesterday',
    createdAt: 'Jun 23, 2025',
    starred: false,
    shared: true,
    parentFolderId: null,
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },

  // Files (at root)
  {
    id: 'file1',
    name: 'Brand_Logo.png',
    type: 'png',
    size: '2.1 MB',
    sizeBytes: 2100000,
    modifiedAt: '2h ago',
    createdAt: 'Jun 24, 2025',
    starred: true,
    shared: true,
    parentFolderId: null,
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },
  {
    id: 'file2',
    name: 'Contract_v4.pdf',
    type: 'pdf',
    size: '14.8 MB',
    sizeBytes: 14800000,
    modifiedAt: 'Yesterday',
    createdAt: 'Jun 23, 2025',
    starred: false,
    shared: false,
    parentFolderId: null,
    isTrash: false,
    owner: { name: 'Sarah Connor', avatar: 'SC', email: 'sarah@nexus.com' },
  },
  {
    id: 'file3',
    name: 'Notes.docx',
    type: 'docx',
    size: '142 KB',
    sizeBytes: 142000,
    modifiedAt: 'Monday',
    createdAt: 'Jun 22, 2025',
    starred: true,
    shared: false,
    parentFolderId: null,
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },
  {
    id: 'file4',
    name: 'Q3_Report.xlsx',
    type: 'xlsx',
    size: '312 KB',
    sizeBytes: 312000,
    modifiedAt: '3d ago',
    createdAt: 'Jun 21, 2025',
    starred: false,
    shared: true,
    parentFolderId: null,
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },
  {
    id: 'file5',
    name: 'Promo_Video.mp4',
    type: 'mp4',
    size: '145 MB',
    sizeBytes: 145000000,
    modifiedAt: 'Last week',
    createdAt: 'Jun 17, 2025',
    starred: false,
    shared: false,
    parentFolderId: null,
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },
  {
    id: 'file6',
    name: 'archive_2025.zip',
    type: 'zip',
    size: '1.4 GB',
    sizeBytes: 1400000000,
    modifiedAt: 'Sep 28',
    createdAt: 'Sep 28, 2024',
    starred: false,
    shared: false,
    parentFolderId: null,
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },

  // Inside Brand_Assets (f1)
  {
    id: 'b1',
    name: 'Logo_Dark_Theme.png',
    type: 'png',
    size: '1.2 MB',
    sizeBytes: 1200000,
    modifiedAt: '2h ago',
    createdAt: 'Jun 24, 2025',
    starred: true,
    shared: true,
    parentFolderId: 'f1',
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },
  {
    id: 'b2',
    name: 'Color_Palette.pdf',
    type: 'pdf',
    size: '4.5 MB',
    sizeBytes: 4500000,
    modifiedAt: 'Yesterday',
    createdAt: 'Jun 23, 2025',
    starred: false,
    shared: true,
    parentFolderId: 'f1',
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },
  {
    id: 'b3',
    name: 'Brand_Guidelines.docx',
    type: 'docx',
    size: '8.4 MB',
    sizeBytes: 8400000,
    modifiedAt: 'Last week',
    createdAt: 'Jun 15, 2025',
    starred: true,
    shared: false,
    parentFolderId: 'f1',
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },
  {
    id: 'b4',
    name: 'Social_Post_Template.png',
    type: 'png',
    size: '942 KB',
    sizeBytes: 942000,
    modifiedAt: '3d ago',
    createdAt: 'Jun 21, 2025',
    starred: false,
    shared: false,
    parentFolderId: 'f1',
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  },

  // Inside Project_Nexus (f2)
  {
    id: 'n1',
    name: 'Nexus_Brief.docx',
    type: 'docx',
    size: '48 KB',
    sizeBytes: 48000,
    modifiedAt: '3d ago',
    createdAt: 'Jun 21, 2025',
    starred: false,
    shared: false,
    parentFolderId: 'f2',
    isTrash: false,
    owner: { name: 'Sarah Connor', avatar: 'SC', email: 'sarah@nexus.com' },
  },
  {
    id: 'n2',
    name: 'Architecture_v1.pdf',
    type: 'pdf',
    size: '2.8 MB',
    sizeBytes: 2800000,
    modifiedAt: '5d ago',
    createdAt: 'Jun 19, 2025',
    starred: true,
    shared: false,
    parentFolderId: 'f2',
    isTrash: false,
    owner: { name: 'Ethan Li', avatar: 'EL', email: 'Ethan7586@gsyen.com' },
  }
];

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  { id: 'act1', user: 'Ethan Li', action: 'uploaded Brand_Logo.png', time: '2 hours ago' },
  { id: 'act2', user: 'Sarah Connor', action: 'commented on Contract_v4.pdf', time: 'Yesterday' },
  { id: 'act3', user: 'Ethan Li', action: 'moved Brand_Logo.png to Brand_Assets', time: '3 days ago' },
  { id: 'act4', user: 'Ethan Li', action: 'created folder Project_Nexus', time: 'May 12, 2025' }
];

export const INITIAL_COMMENTS: Record<string, CommentItem[]> = {
  'file1': [
    { id: 'c1', user: 'Ethan Li', avatar: 'EL', text: 'This looks pixel perfect in high contrast theme!', time: '2h ago' }
  ],
  'file2': [
    { id: 'c2', user: 'Sarah Connor', avatar: 'SC', text: 'Please review section 4 carefully before signing.', time: 'Yesterday' },
    { id: 'c3', user: 'Ethan Li', avatar: 'EL', text: 'Looks correct, I will share with our legal team.', time: 'Yesterday' }
  ]
};
