import type { ActivityEvent, FileItem, StorageBucket } from "@gyenbox/types"

const now = Date.now()

export const mockFiles: FileItem[] = [
  {
    id: "fld_strategy",
    name: "GSYEN Strategy",
    kind: "folder",
    size: 0,
    ownerName: "Ethan",
    updatedAt: new Date(now - 1000 * 60 * 28).toISOString(),
    isStarred: true,
    isShared: true,
    path: "/My files",
    tags: ["team", "strategy"],
  },
  {
    id: "file_board_pack",
    name: "Q4-board-pack.pdf",
    kind: "pdf",
    mimeType: "application/pdf",
    size: 14_208_000,
    ownerName: "Ethan",
    updatedAt: new Date(now - 1000 * 60 * 90).toISOString(),
    isStarred: true,
    isShared: true,
    path: "/GSYEN Strategy",
    tags: ["board", "finance"],
  },
  {
    id: "file_map",
    name: "territory-map.png",
    kind: "image",
    mimeType: "image/png",
    size: 8_144_944,
    ownerName: "Mina",
    updatedAt: new Date(now - 1000 * 60 * 240).toISOString(),
    isStarred: false,
    isShared: true,
    path: "/Brand",
    tags: ["brand", "map"],
  },
  {
    id: "file_contract",
    name: "vendor-data-processing-agreement.docx",
    kind: "document",
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size: 812_331,
    ownerName: "Legal",
    updatedAt: new Date(now - 1000 * 60 * 60 * 9).toISOString(),
    isStarred: false,
    isShared: false,
    path: "/Legal",
    tags: ["contract"],
  },
  {
    id: "file_model",
    name: "usage-breakdown.xlsx",
    kind: "spreadsheet",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size: 2_620_000,
    ownerName: "Finance",
    updatedAt: new Date(now - 1000 * 60 * 60 * 26).toISOString(),
    isStarred: false,
    isShared: true,
    path: "/Finance",
    tags: ["quota", "usage"],
  },
  {
    id: "file_api",
    name: "sync-api-contract.ts",
    kind: "code",
    mimeType: "text/typescript",
    size: 48_220,
    ownerName: "Platform",
    updatedAt: new Date(now - 1000 * 60 * 60 * 42).toISOString(),
    isStarred: true,
    isShared: false,
    path: "/Engineering",
    tags: ["api", "sync"],
  },
]

export const mockActivity: ActivityEvent[] = [
  {
    id: "act_1",
    actor: "Mina",
    action: "shared",
    resourceName: "territory-map.png",
    createdAt: new Date(now - 1000 * 60 * 24).toISOString(),
  },
  {
    id: "act_2",
    actor: "Ethan",
    action: "named version",
    resourceName: "Q4-board-pack.pdf",
    createdAt: new Date(now - 1000 * 60 * 86).toISOString(),
  },
  {
    id: "act_3",
    actor: "Platform",
    action: "created folder",
    resourceName: "Engineering",
    createdAt: new Date(now - 1000 * 60 * 210).toISOString(),
  },
]

export const storageBuckets: StorageBucket[] = [
  { label: "Documents", bytes: 18_100_000_000, color: "#6B5CE7" },
  { label: "Images", bytes: 9_700_000_000, color: "#22C97A" },
  { label: "Video", bytes: 11_400_000_000, color: "#F5A623" },
  { label: "Other", bytes: 2_000_000_000, color: "#8888A8" },
]
