steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/keep/Dockerfile
      - --target
      - runner
      - -t
      - asia-east1-docker.pkg.dev/gyenbox/cloud-run-source-deploy/gyenbox-keep:${_IMAGE_TAG}
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_URL=https://hrtynofmjcumuanjvpxz.supabase.co
      - --build-arg
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY
      - .
images:
  - asia-east1-docker.pkg.dev/gyenbox/cloud-run-source-deploy/gyenbox-keep:${_IMAGE_TAG}
