import { FileItem } from './types';

export const INITIAL_FILES: FileItem[] = [
  // Folders (in root)
  {
    id: 'folder-brand-assets',
    name: 'Brand_Assets',
    type: 'folder',
    parentId: null,
    size: '4.8 GB',
    sizeBytes: 5153960755,
    modifiedText: '3h ago',
    createdDate: 'Jun 12, 2025',
    itemCount: 45,
    isStarred: true,
    tags: ['design', 'brand', 'marketing'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },
  {
    id: 'folder-project-nexus',
    name: 'Project_Nexus',
    type: 'folder',
    parentId: null,
    size: '1.2 GB',
    sizeBytes: 1288490188,
    modifiedText: 'Yesterday',
    createdDate: 'Jun 20, 2025',
    itemCount: 12,
    isStarred: false,
    tags: ['development', 'internal'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },
  {
    id: 'folder-exports',
    name: 'Exports',
    type: 'folder',
    parentId: null,
    size: '320 MB',
    sizeBytes: 335544320,
    modifiedText: '3 days ago',
    createdDate: 'Jun 22, 2025',
    itemCount: 8,
    isStarred: false,
    tags: ['exports', 'delivery'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },

  // Files (in root)
  {
    id: 'file-brand-logo',
    name: 'Brand_Logo.png',
    type: 'png',
    parentId: null,
    size: '2.1 MB',
    sizeBytes: 2202009,
    modifiedText: '2h ago',
    createdDate: 'Jun 24, 2025',
    isStarred: true,
    isRecent: true,
    badge: 'PNG',
    tags: ['design', 'brand', 'logo'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },
  {
    id: 'file-contract-v4',
    name: 'Contract_v4.pdf',
    type: 'pdf',
    parentId: null,
    size: '14.8 MB',
    sizeBytes: 15518924,
    modifiedText: 'Yesterday',
    createdDate: 'Jun 23, 2025',
    isStarred: false,
    isRecent: true,
    badge: 'PDF',
    tags: ['legal', 'contract'],
    ownerName: 'Sophia Chen',
    ownerAvatar: 'SC'
  },
  {
    id: 'file-notes',
    name: 'Notes.docx',
    type: 'docx',
    parentId: null,
    size: '142 KB',
    sizeBytes: 145408,
    modifiedText: 'Monday',
    createdDate: 'Jun 22, 2025',
    isStarred: true,
    isRecent: true,
    badge: 'DOC',
    tags: ['notes', 'draft'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },
  {
    id: 'file-q3-report',
    name: 'Q3_Report.xlsx',
    type: 'xlsx',
    parentId: null,
    size: '312 KB',
    sizeBytes: 319488,
    modifiedText: '3d ago',
    createdDate: 'Jun 21, 2025',
    isStarred: false,
    isRecent: true,
    badge: 'XLS',
    tags: ['financial', 'report'],
    ownerName: 'Marcus Vance',
    ownerAvatar: 'MV'
  },
  {
    id: 'file-promo-video',
    name: 'Promo_Video.mp4',
    type: 'mp4',
    parentId: null,
    size: '145 MB',
    sizeBytes: 152043520,
    modifiedText: 'Last week',
    createdDate: 'Jun 17, 2025',
    isStarred: true,
    isRecent: true,
    badge: 'MP4',
    tags: ['marketing', 'video'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },
  {
    id: 'file-archive-2025',
    name: 'archive_2025.zip',
    type: 'zip',
    parentId: null,
    size: '1.4 GB',
    sizeBytes: 1503238553,
    modifiedText: 'Sep 28, 2025',
    createdDate: 'Sep 28, 2025',
    isStarred: false,
    isRecent: true,
    badge: 'ZIP',
    tags: ['archive', 'backup'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },

  // Subfiles inside Brand_Assets
  {
    id: 'sub-brand-assets-1',
    name: 'Brand_Identity_v2.pdf',
    type: 'pdf',
    parentId: 'folder-brand-assets',
    size: '22.4 MB',
    sizeBytes: 23488102,
    modifiedText: 'Jun 13, 2025',
    createdDate: 'Jun 13, 2025',
    badge: 'PDF',
    tags: ['brand', 'guidelines'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },
  {
    id: 'sub-brand-assets-2',
    name: 'Typography_Specs.docx',
    type: 'docx',
    parentId: 'folder-brand-assets',
    size: '1.1 MB',
    sizeBytes: 1153433,
    modifiedText: 'Jun 14, 2025',
    createdDate: 'Jun 14, 2025',
    badge: 'DOC',
    tags: ['typography', 'design'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },
  {
    id: 'sub-brand-assets-3',
    name: 'Hero_Illustration.png',
    type: 'png',
    parentId: 'folder-brand-assets',
    size: '8.4 MB',
    sizeBytes: 8808038,
    modifiedText: 'Jun 15, 2025',
    createdDate: 'Jun 15, 2025',
    badge: 'PNG',
    tags: ['design', 'illustration'],
    ownerName: 'Sophia Chen',
    ownerAvatar: 'SC'
  },

  // Subfiles inside Project_Nexus
  {
    id: 'sub-project-nexus-1',
    name: 'System_Architecture_Draft.png',
    type: 'png',
    parentId: 'folder-project-nexus',
    size: '4.2 MB',
    sizeBytes: 4404019,
    modifiedText: 'Jun 20, 2025',
    createdDate: 'Jun 20, 2025',
    badge: 'PNG',
    tags: ['architecture', 'tech'],
    ownerName: 'Ethan Li',
    ownerAvatar: 'EL'
  },
  {
    id: 'sub-project-nexus-2',
    name: 'Sprint_Timeline.xlsx',
    type: 'xlsx',
    parentId: 'folder-project-nexus',
    size: '85 KB',
    sizeBytes: 87040,
    modifiedText: 'Jun 21, 2025',
    createdDate: 'Jun 21, 2025',
    badge: 'XLS',
    tags: ['timeline', 'sprint'],
    ownerName: 'Marcus Vance',
    ownerAvatar: 'MV'
  }
];
